### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by ar06x** [aerospaceresearch/VisMa#217]
```C:\Users\wolfy.DESKTOP-0QI782C\Downloads\visma-master\visma-master>python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from visma.gui.window import initGUI
  File "C:\Users\wolfy.DESKTOP-0QI782C\Downloads\visma-master\visma-master\visma\gui\window.py", line 11, in <module>
    from PyQt5.QtGui import QPainter
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by mighty-phoenix** [comment]
@wolfy01 DId you install the requirements first?
Kindly refer the instructions mentioned in the [README.md](https://github.com/aerospaceresearch/visma/blob/master/README.md) file

**Comment by archithadge** [comment]
@wolfy01 I had the same issue. Install it for development from this link
[https://github.com/aerospaceresearch/visma/archive/master.zip]

and run the following command
pip install -r requirements.txt

and run main.py from it.

**Comment by ar06x** [comment]
Didn't seem to fix it...

```wolfy3543@penguin:~/visma-master$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from visma.gui.cli import commandExec
  File "/home/wolfy3543/visma-master/visma/gui/cli.py", line 3, in <module>
    from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QTabWidget, QVBoxLayout
ImportError: No module named PyQt5.QtWidgets
```

**Comment by mayankDhiman** [comment]
Hi, thanks for opening this.`pip3 install -r requirements` will fix it. If in any case it doesn't consider installing PyQt5 manually. Please considering discussing on Zulip chat before opening an issue.

**Comment by ar06x** [comment]
Ive tried that too.. Nothing seems to work
