### ISSUE TITLE
Problem In running 

### ISSUE THREAD

**Issue by netkeojas** [aerospaceresearch/VisMa#222]
I tried to run on Ubuntu 18.04 bionic and had the following error

_>>> from visma.main import init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ojas/.local/lib/python3.6/site-packages/visma/main.py", line 4, in <module>
    from visma.gui.window import initGUI
  File "/home/ojas/.local/lib/python3.6/site-packages/visma/gui/window.py", line 16, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'_

**Comment by mayankDhiman** [comment]
`pip3 install -r requirements`, try running this first to install requirements for VisMa. If possible, try discussing the problem on Zulip channel before opening the issue.
