### ISSUE TITLE
Unable to import init on PyQt5 5.15.1

### ISSUE THREAD

**Issue by namanbansalcodes** [aerospaceresearch/VisMa#248]
While running the command `from visma.main import init` on:

`Windows 64-bit
Python 3.7.4`

I got the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\visma\main.py", line 4, in <module>
    from visma.gui.window import initGUI
  File "C:\ProgramData\Anaconda3\lib\site-packages\visma\gui\window.py", line 16, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'`

I am using PyQt5 v5.15.1, however, I was able to open the GUI on PyQt v5.10

Opening this issue to extend support to PyQt v5.15.1

**Comment by Pranoypauljr** [comment]
first of all do work this project in a virtual environment and speaking about the above issue,i also had the same error and resolved it by installing 'PyQtWebEngine' library using pip,just run the below command in cli
->pip install PyQtWebEngine
